name = "kiliman-dev"
type = "javascript"
compatibility_date = "2022-04-05"

zone_id = ""
account_id = "ffc27d2c4ab35f6e6f2dc63e87cd82d3"
route = ""
workers_dev = true

kv_namespaces = [
  { binding = "SESSION", id = "80d5f4694dc04e74a9725a76d42f2ca3" },
  { binding = "REDIRECT", id = "fa27a5210b3845409c039a9669d62f74" },
  { binding = "CONTENT", id = "34dfc5454fe94b5c8ecdbb3a2d7f9cf2" }
]

[site]
bucket = "./public"

[build]
command = "npm run build"

[miniflare]
kv_persist = true